# Generated by Django 2.2.7 on 2019-11-21 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('nombre_genero', models.CharField(help_text='Nombre del género', max_length=50, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
