# Generated by Django 2.2.7 on 2019-11-21 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genero',
            options={'verbose_name': 'Género', 'verbose_name_plural': 'Géneros'},
        ),
        migrations.AlterField(
            model_name='genero',
            name='nombre_genero',
            field=models.CharField(help_text='Nombre del género', max_length=50, unique=True, verbose_name='Nombre géneros'),
        ),
    ]
