# Generated by Django 2.2.7 on 2019-11-21 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0005_auto_20191120_2357'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('id_rfid_cliente', models.CharField(help_text='Id RFID carné o llavero', max_length=50, unique=True, verbose_name='Id RFID cliente')),
                ('numero_documento_identidad_cliente', models.CharField(help_text='Número del documento de identidad del cliente', max_length=15, unique=True, verbose_name='Número de documento de identidad')),
                ('nombres_cliente', models.CharField(help_text='Nombres del cliente', max_length=50, verbose_name='Nombres del cliente')),
                ('apellidos_cliente', models.CharField(help_text='Apellidos del cliente', max_length=50, verbose_name='Apellidos del cliente')),
                ('email_cliente', models.EmailField(help_text='Correo electrónico cliente', max_length=70, verbose_name='Correo electrónico')),
                ('fecha_nacimiento_cliente', models.DateField(verbose_name='Fecha de nacimiento')),
                ('saldo_cliente', models.IntegerField(verbose_name='Saldo cliente')),
                ('dependencia_cliente', models.ForeignKey(help_text='Dependencia a la que pertenece', on_delete=False, to='cliente.Dependencia', verbose_name='Dependencia')),
                ('documento_identidad', models.ForeignKey(help_text='Documento de identidad del cliente', on_delete=False, to='cliente.Documento_identidad', verbose_name='Documento de identidad')),
                ('genero_cliente', models.ForeignKey(help_text='Gérero del cliente', on_delete=False, to='cliente.Genero', verbose_name='Género del cliente')),
                ('tipo_cliente', models.ForeignKey(help_text='Tipo de cliente', on_delete=False, to='cliente.Tipo_cliente', verbose_name='Tipo de cliente')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
