# Generated by Django 2.2.7 on 2019-11-21 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0006_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='apellidos_cliente',
            field=models.CharField(help_text='Apellidos del cliente', max_length=50, verbose_name='Apellidos'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='genero_cliente',
            field=models.ForeignKey(help_text='Gérero del cliente', on_delete=False, to='cliente.Genero', verbose_name='Género'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='id_rfid_cliente',
            field=models.CharField(help_text='Id RFID carné o llavero', max_length=50, unique=True, verbose_name='Id RFID'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nombres_cliente',
            field=models.CharField(help_text='Nombres del cliente', max_length=50, verbose_name='Nombres'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='saldo_cliente',
            field=models.IntegerField(verbose_name='Saldo'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='tipo_cliente',
            field=models.ForeignKey(help_text='Tipo de cliente', on_delete=False, to='cliente.Tipo_cliente', verbose_name='Tipo'),
        ),
    ]
