# Generated by Django 2.2.7 on 2019-11-21 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('afiliacion', '0002_auto_20191121_0255'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consumo_Servicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('valor_cancelado_servicio', models.PositiveIntegerField(help_text='Valor cancelado por el cliente por el servicio recibido')),
                ('afiliacion_servicio', models.ForeignKey(help_text='Servicio afiliado recibido', on_delete=False, to='afiliacion.Afiliacion_servicio', verbose_name='Servicio afiliado')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
