# Generated by Django 2.2.7 on 2019-11-21 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('nombre_servicio', models.CharField(help_text='Nombre del servicio de alimentación', max_length=50, verbose_name='Nombre del servicio')),
                ('hora_inicio', models.TimeField(help_text='Hora en que comienza la entrega del servicio', verbose_name='Hora inicio entrega')),
                ('hora_fin', models.TimeField(help_text='Hora en que finaliza la entrega del servicio', verbose_name='Hora finalización entrega')),
                ('valor_servicio', models.PositiveIntegerField(help_text='Valor en pesos colombianos que se debe cancelar por el servicio', verbose_name='Valor servicio')),
                ('lunes', models.BooleanField(default=True)),
                ('martes', models.BooleanField(default=True)),
                ('miercoles', models.BooleanField(default=True)),
                ('jueves', models.BooleanField(default=True)),
                ('viernes', models.BooleanField(default=True)),
                ('sabado', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Registro_servicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('fecha_servicio', models.DateField(help_text='Fecha del servicio', verbose_name='Fecha del servicio')),
                ('servicio_cancelado', models.BooleanField(default=False, help_text='True si se cancela el servicio', verbose_name='Servicio cancelado')),
                ('servicio', models.ForeignKey(help_text='Servicio que se va a registrar', on_delete=False, to='Servicios.Servicio', verbose_name='Servicio')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
