# Generated by Django 2.2.7 on 2019-11-21 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Servicios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registro_servicio',
            options={'verbose_name': 'Registro servicio', 'verbose_name_plural': 'Registro de servicios'},
        ),
        migrations.RenameField(
            model_name='servicio',
            old_name='jueves',
            new_name='servicio_jueves',
        ),
        migrations.RenameField(
            model_name='servicio',
            old_name='lunes',
            new_name='servicio_lunes',
        ),
        migrations.RenameField(
            model_name='servicio',
            old_name='martes',
            new_name='servicio_martes',
        ),
        migrations.RenameField(
            model_name='servicio',
            old_name='miercoles',
            new_name='servicio_miercoles',
        ),
        migrations.RenameField(
            model_name='servicio',
            old_name='sabado',
            new_name='servicio_sabado',
        ),
        migrations.RenameField(
            model_name='servicio',
            old_name='viernes',
            new_name='servicio_viernes',
        ),
    ]
