# Generated by Django 2.2.7 on 2019-11-21 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cliente', '0007_auto_20191121_0036'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recarga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('valor_recarga', models.IntegerField(help_text='Valor de la recarga en pesos colombianos', verbose_name='Valor de la recarga')),
                ('cliente_recarga', models.ForeignKey(help_text='Cliente al que se le realiza la recarga', on_delete=False, to='cliente.Cliente', verbose_name='Cliente recarga')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
