# Generated by Django 2.2.7 on 2019-11-21 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Servicios', '0002_auto_20191121_0233'),
        ('cliente', '0007_auto_20191121_0036'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo_afiliacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('nombre_tipo_afiliacion', models.CharField(help_text='Nombre del tipo de afiliación', max_length=50, verbose_name='Nombre de afiliación')),
                ('valor_porcentaje_descuento', models.IntegerField(help_text='Valor del porcentaje de descuento', verbose_name='Valor porcentaje de descuento')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Afiliacion_servicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('afiliacion_activa', models.BooleanField(default=True, help_text='La afiliación se encuentra activa', verbose_name='Afiliación activa')),
                ('afiliacion_lunes', models.BooleanField(default=True)),
                ('afiliacion_martes', models.BooleanField(default=True)),
                ('afiliacion_miercoles', models.BooleanField(default=True)),
                ('afiliacion_jueves', models.BooleanField(default=True)),
                ('afiliacion_viernes', models.BooleanField(default=True)),
                ('afiliacion_sabado', models.BooleanField(default=True)),
                ('fallas_mensuales_afiliacion', models.PositiveIntegerField(help_text='Número de fallas al servicio afiliado del mes actual', verbose_name='Fallas mensuales afiliación')),
                ('fallas_acumuladas_afiliacion', models.PositiveIntegerField(help_text='Número de fallas acumuladas del servicio afiliado', verbose_name='Fallas acumuladas afiliación')),
                ('cliente_afiliacion', models.ForeignKey(help_text='Cliente que se va afiliar', on_delete=False, to='cliente.Cliente', verbose_name='Cliente afiliación')),
                ('servicio_afiliacion', models.ForeignKey(help_text='Servicio al que se va a afiliar el cliente', on_delete=False, to='Servicios.Servicio', verbose_name='Servicio afiliación')),
                ('tipo_afiliacion', models.ForeignKey(help_text='Tipo de afiliación del servicio', on_delete=False, to='afiliacion.Tipo_afiliacion', verbose_name='Tipo de afiliación')),
            ],
            options={
                'verbose_name': 'Afiliación servicio',
                'verbose_name_plural': 'Afiliación servicios',
            },
        ),
    ]
