# Generated by Django 2.2.7 on 2019-11-21 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('afiliacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipo_afiliacion',
            options={'verbose_name': 'Tipo de afiliación', 'verbose_name_plural': 'Tipos de afiliación'},
        ),
    ]
