# Generated by Django 2.2.7 on 2019-11-21 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('afiliacion', '0002_auto_20191121_0255'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo_sancion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('nombre_sancion', models.CharField(help_text='Nombre de la sanción', max_length=50, verbose_name='Nombre sanción')),
                ('duracion_sancion', models.IntegerField(help_text='Cantidad de días que dura la sanción', verbose_name='Duración sanción')),
            ],
            options={
                'verbose_name': 'Tipo de sanción',
                'verbose_name_plural': 'Tipos de sanción',
            },
        ),
        migrations.CreateModel(
            name='Sancion_cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('descripcion_sancion_cliente', models.TextField(help_text='Descripción de la sanción', verbose_name='Descripción de la sanción')),
                ('afiliacion_servicio_sancion_cliente', models.ForeignKey(help_text='Afiliación servicio a la que se aplica la sanción', on_delete=False, to='afiliacion.Afiliacion_servicio', verbose_name='Sanción cliente')),
                ('tipo_sancion', models.ForeignKey(help_text='Tipo de sanción que se va a aplicar', on_delete=False, to='Sanciones.Tipo_sancion', verbose_name='Tipo de sanción')),
            ],
            options={
                'verbose_name': 'Sanción cliente',
                'verbose_name_plural': 'Sanciones cliente',
            },
        ),
    ]
